
export const CartActionTypes = {

    SET_CART_HIDDEN: 'SET_CART_HIDDEN',
    SET_ADD_CART_ITEM: 'SET_ADD_CART_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART'
}